<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />




<title>Delineamento inteiramente casualizado</title>

<script src="site_libs/header-attrs-2.25/header-attrs.js"></script>
<script src="site_libs/jquery-3.6.0/jquery-3.6.0.min.js"></script>
<meta name="viewport" content="width=device-width, initial-scale=1" />
<link href="site_libs/bootstrap-3.3.5/css/flatly.min.css" rel="stylesheet" />
<script src="site_libs/bootstrap-3.3.5/js/bootstrap.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/html5shiv.min.js"></script>
<script src="site_libs/bootstrap-3.3.5/shim/respond.min.js"></script>
<style>h1 {font-size: 34px;}
       h1.title {font-size: 38px;}
       h2 {font-size: 30px;}
       h3 {font-size: 24px;}
       h4 {font-size: 18px;}
       h5 {font-size: 16px;}
       h6 {font-size: 12px;}
       code {color: inherit; background-color: rgba(0, 0, 0, 0.04);}
       pre:not([class]) { background-color: white }</style>
<script src="site_libs/jqueryui-1.13.2/jquery-ui.min.js"></script>
<link href="site_libs/tocify-1.9.1/jquery.tocify.css" rel="stylesheet" />
<script src="site_libs/tocify-1.9.1/jquery.tocify.js"></script>
<script src="site_libs/navigation-1.1/tabsets.js"></script>
<link href="site_libs/highlightjs-9.12.0/default.css" rel="stylesheet" />
<script src="site_libs/highlightjs-9.12.0/highlight.js"></script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>

<style type="text/css">code{white-space: pre;}</style>
<script type="text/javascript">
if (window.hljs) {
  hljs.configure({languages: []});
  hljs.initHighlightingOnLoad();
  if (document.readyState && document.readyState === "complete") {
    window.setTimeout(function() { hljs.initHighlighting(); }, 0);
  }
}
</script>









<style type = "text/css">
.main-container {
  max-width: 940px;
  margin-left: auto;
  margin-right: auto;
}
img {
  max-width:100%;
}
.tabbed-pane {
  padding-top: 12px;
}
.html-widget {
  margin-bottom: 20px;
}
button.code-folding-btn:focus {
  outline: none;
}
summary {
  display: list-item;
}
details > summary > p:only-child {
  display: inline;
}
pre code {
  padding: 0;
}
</style>


<style type="text/css">
.dropdown-submenu {
  position: relative;
}
.dropdown-submenu>.dropdown-menu {
  top: 0;
  left: 100%;
  margin-top: -6px;
  margin-left: -1px;
  border-radius: 0 6px 6px 6px;
}
.dropdown-submenu:hover>.dropdown-menu {
  display: block;
}
.dropdown-submenu>a:after {
  display: block;
  content: " ";
  float: right;
  width: 0;
  height: 0;
  border-color: transparent;
  border-style: solid;
  border-width: 5px 0 5px 5px;
  border-left-color: #cccccc;
  margin-top: 5px;
  margin-right: -10px;
}
.dropdown-submenu:hover>a:after {
  border-left-color: #adb5bd;
}
.dropdown-submenu.pull-left {
  float: none;
}
.dropdown-submenu.pull-left>.dropdown-menu {
  left: -100%;
  margin-left: 10px;
  border-radius: 6px 0 6px 6px;
}
</style>

<script type="text/javascript">
// manage active state of menu based on current page
$(document).ready(function () {
  // active menu anchor
  href = window.location.pathname
  href = href.substr(href.lastIndexOf('/') + 1)
  if (href === "")
    href = "index.html";
  var menuAnchor = $('a[href="' + href + '"]');

  // mark the anchor link active (and if it's in a dropdown, also mark that active)
  var dropdown = menuAnchor.closest('li.dropdown');
  if (window.bootstrap) { // Bootstrap 4+
    menuAnchor.addClass('active');
    dropdown.find('> .dropdown-toggle').addClass('active');
  } else { // Bootstrap 3
    menuAnchor.parent().addClass('active');
    dropdown.addClass('active');
  }

  // Navbar adjustments
  var navHeight = $(".navbar").first().height() + 15;
  var style = document.createElement('style');
  var pt = "padding-top: " + navHeight + "px; ";
  var mt = "margin-top: -" + navHeight + "px; ";
  var css = "";
  // offset scroll position for anchor links (for fixed navbar)
  for (var i = 1; i <= 6; i++) {
    css += ".section h" + i + "{ " + pt + mt + "}\n";
  }
  style.innerHTML = "body {" + pt + "padding-bottom: 40px; }\n" + css;
  document.head.appendChild(style);
});
</script>

<!-- tabsets -->

<style type="text/css">
.tabset-dropdown > .nav-tabs {
  display: inline-table;
  max-height: 500px;
  min-height: 44px;
  overflow-y: auto;
  border: 1px solid #ddd;
  border-radius: 4px;
}

.tabset-dropdown > .nav-tabs > li.active:before, .tabset-dropdown > .nav-tabs.nav-tabs-open:before {
  content: "\e259";
  font-family: 'Glyphicons Halflings';
  display: inline-block;
  padding: 10px;
  border-right: 1px solid #ddd;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li.active:before {
  content: "\e258";
  font-family: 'Glyphicons Halflings';
  border: none;
}

.tabset-dropdown > .nav-tabs > li.active {
  display: block;
}

.tabset-dropdown > .nav-tabs > li > a,
.tabset-dropdown > .nav-tabs > li > a:focus,
.tabset-dropdown > .nav-tabs > li > a:hover {
  border: none;
  display: inline-block;
  border-radius: 4px;
  background-color: transparent;
}

.tabset-dropdown > .nav-tabs.nav-tabs-open > li {
  display: block;
  float: none;
}

.tabset-dropdown > .nav-tabs > li {
  display: none;
}
</style>

<!-- code folding -->



<style type="text/css">

#TOC {
  margin: 25px 0px 20px 0px;
}
@media (max-width: 768px) {
#TOC {
  position: relative;
  width: 100%;
}
}

@media print {
.toc-content {
  /* see https://github.com/w3c/csswg-drafts/issues/4434 */
  float: right;
}
}

.toc-content {
  padding-left: 30px;
  padding-right: 40px;
}

div.main-container {
  max-width: 1200px;
}

div.tocify {
  width: 20%;
  max-width: 260px;
  max-height: 85%;
}

@media (min-width: 768px) and (max-width: 991px) {
  div.tocify {
    width: 25%;
  }
}

@media (max-width: 767px) {
  div.tocify {
    width: 100%;
    max-width: none;
  }
}

.tocify ul, .tocify li {
  line-height: 20px;
}

.tocify-subheader .tocify-item {
  font-size: 0.90em;
}

.tocify .list-group-item {
  border-radius: 0px;
}


</style>



</head>

<body>


<div class="container-fluid main-container">


<!-- setup 3col/9col grid for toc_float and main content  -->
<div class="row">
<div class="col-xs-12 col-sm-4 col-md-3">
<div id="TOC" class="tocify">
</div>
</div>

<div class="toc-content col-xs-12 col-sm-8 col-md-9">




<div class="navbar navbar-default  navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-bs-toggle="collapse" data-target="#navbar" data-bs-target="#navbar">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="index.html">Estatística experimental</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
        <li>
  <a href="index.html">Sobre</a>
</li>
<li>
  <a href="revisao.html">Revisão</a>
</li>
<li class="dropdown">
  <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Capítulos
     
    <span class="caret"></span>
  </a>
  <ul class="dropdown-menu" role="menu">
    <li>
      <a href="introducao.html">Introdução</a>
    </li>
    <li>
      <a href="dic.html">Delineamento inteiramente casualizado</a>
    </li>
    <li>
      <a href="cm.html">Comparação de médias</a>
    </li>
    <li>
      <a href="rp.html">Regressão polinomial</a>
    </li>
    <li>
      <a href="anova.html">Pressuposições da Anova</a>
    </li>
    <li>
      <a href="dbc.html">Delineamento blocos casualizados</a>
    </li>
    <li>
      <a href="dql.html">Delineamento quadrado latino</a>
    </li>
    <li>
      <a href="fat.html">Esquema fatorial de tratamentos</a>
    </li>
    <li>
      <a href="parcs.html">Parcelas subdivididas</a>
    </li>
    <li>
      <a href="grups.html">Grupos de experimentos</a>
    </li>
  </ul>
</li>
<li>
  <a href="https://davivitti.shinyapps.io/atividades/">Atividades</a>
</li>
<li>
  <a href="https://forms.gle/LQ6mNE4DoR1Fk6px6">Dúvidas?</a>
</li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <li>
  <a href="https://forms.gle/LQ6mNE4DoR1Fk6px6">Prof. Drª Renata A. Sermarini</a>
</li>
      </ul>
    </div><!--/.nav-collapse -->
  </div><!--/.container -->
</div><!--/.navbar -->

<div id="header">



<h1 class="title toc-ignore">Delineamento inteiramente casualizado</h1>

</div>


<style type="text/css">
body {
     text-align: justify;
}

</style>
<div id="fundamentos" class="section level1">
<h1>Fundamentos</h1>
<div class="line-block">     O delineamento inteiramente casualizado
(DIC) é o mais simples dos delineamentos, pois considera apenas dois dos
princípios básicos da experimentação: a repetição e a casualização.
Neste, os tratamentos são aleatoriamente atribuídos ao material
experimental, sem o esforço de se restringir os tratamentos a alguma
porção de área, material ou espaço. Ainda como característica, como não
há uso do controle local o número de repetições por tratamento pode
variar.É geralmente utilizado quando a variação do material experimental
é relativamente pequena, o que geralmente ocorre em laboratórios e casas
de vegetação.</div>
<div class="line-block">     Como vantagens de sua utilização temos que
é um experimento de fácil planejamento e que permite o número máximo de
graus de liberdade do Resíduo. Em termos de análise é a mais simples
quando comparado aos demais delineamentos experimentais e não
apresentará confundimento caso os tratamentos tenham números diferentes
de repetições. Entretanto, como desvantagens temos que o delineamento
inteiramente casualizado é adequado aos experimentos com baixo número de
tratamentos e material experimental homogêneo, o que nem sempre se
consegue. Quando um grande número de tratamentos é utilizado, há um
crescimento no material experimental, que pode inflacionar a variação
experimental. Nesses casos o Delineamento Inteiramente Casualizado não é
indicado.</div>
<div class="line-block"><br />
<br />
</div>
<div id="exemplo-vinhedo" class="section level2">
<h2>Exemplo: Vinhedo</h2>
<div class="float">
<img src="figs/CRD.png"
alt="Photos and illustrations by Hemant Gohil." />
<div class="figcaption">Photos and illustrations by Hemant Gohil.</div>
</div>
<p>Figura 1: Dois experimentos em DIC com quatro repetições de um
tratamento (linhas amarelas) e de um controle (linhas azuis), sendo um
em um vinhedo pequeno (A) e outro em um vinhedo médio (C). Fonte: Hemant
Gohil.</p>
<div class="line-block">     Considerações:</div>
<ul>
<li><p>Note que os exemplos consideram uma linha de bordadura entre as
linhas.</p></li>
<li><p>Em alguns casos o mesmo tratamento ocupa parcelas vizinhas
.</p></li>
<li><p>Os croquis para os ensaios mostrados em A e C são exibidos em B e
D, respectivamente.</p></li>
</ul>
<div class="line-block"><br />
<br />
</div>
</div>
</div>
<div id="obtendo-um-croqui-para-um-dic" class="section level1">
<h1>Obtendo um croqui para um DIC</h1>
<div class="line-block">     Para obtermos um croqui para um experimento
com <span class="math inline">\(I\)</span> tratamentos em um DIC, sendo
o <span class="math inline">\(i\)</span>-ésimo tratamento repetido <span
class="math inline">\(n_i\)</span> vezes e o número total de parcelas
<span class="math inline">\(n=\sum_{i=1}^I n_i \text{(1)}\)</span></div>
<ol style="list-style-type: lower-roman">
<li>Enumerar as parcelas 1, 2, . . . , <span
class="math inline">\(n\)</span></li>
<li>Criar o delineamento sistemático, ou seja, alocar o tratamento 1 às
parcelas 1, 2, . . . , <span class="math inline">\(n_1\)</span> alocar o
tratamento 2 às parcelas <span class="math inline">\(n_1\)</span> + 1,
<span class="math inline">\(n_1\)</span> + 2, . . . , <span
class="math inline">\(n_1\)</span> + <span
class="math inline">\(n_2\)</span> e assim até as repetições do
tratamento <span class="math inline">\(I\)</span>.</li>
<li>Escolha uma permutação de 1, 2, . . . , <span
class="math inline">\(n\)</span> e aplique ao delineamento.</li>
</ol>
<div class="line-block"><br />
<br />
</div>
<div id="exemplo" class="section level2">
<h2>Exemplo</h2>
<div class="line-block">     Suponha que desejamos comparar a
produtividade de três variedades de soja, com três, quatro e três
repetições respectivamente. O plano de casualização para o delineamento
sistemático é dado por:</div>
<table>
<colgroup>
<col width="21%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th>Ordem Padrão</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Variedade</td>
<td>A</td>
<td>A</td>
<td>A</td>
<td>B</td>
<td>B</td>
<td>B</td>
<td>B</td>
<td>C</td>
<td>C</td>
<td>C</td>
</tr>
</tbody>
</table>
<p>Uma permutação:</p>
<table>
<colgroup>
<col width="21%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
<col width="7%" />
</colgroup>
<thead>
<tr class="header">
<th>Parcelas</th>
<th>7</th>
<th>1</th>
<th>8</th>
<th>10</th>
<th>3</th>
<th>2</th>
<th>4</th>
<th>6</th>
<th>9</th>
<th>5</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Ordem Padrão</td>
<td>1</td>
<td>2</td>
<td>3</td>
<td>4</td>
<td>5</td>
<td>6</td>
<td>7</td>
<td>8</td>
<td>9</td>
<td>10</td>
</tr>
</tbody>
</table>
<p>E o plano de casualização é dado por:</p>
<table style="width:100%;">
<colgroup>
<col width="18%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
<col width="8%" />
</colgroup>
<thead>
<tr class="header">
<th>Parcelas</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>6</th>
<th>7</th>
<th>8</th>
<th>9</th>
<th>10</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Variedade</td>
<td>B</td>
<td>A</td>
<td>C</td>
<td>C</td>
<td>A</td>
<td>A</td>
<td>B</td>
<td>B</td>
<td>C</td>
<td>A</td>
</tr>
</tbody>
</table>
<div class="line-block"><br />
<br />
</div>
</div>
</div>
<div id="análise-dos-dados" class="section level1">
<h1>Análise dos dados</h1>
<div class="line-block">     Entende-se como objetivo inicial de um
experimento a verificação dos efeitos de tratamentos. Aqui será
utilizada a Análise de Variância (ANOVA) para tal verificação. A ANOVA é
utilizada na comparação de médias de dois ou mais tratamentos ou teste
para a variância dos tratamentos, por meio do teste F (Fisher). Trata-se
de uma extensão do teste t de Student, permitindo que o pesquisador
compare qualquer número de médias, quando o efeito de tratamentos é
fixo.</div>
<div class="line-block"><br />
<br />
</div>
<div id="modelo-estatistico" class="section level2">
<h2>Modelo estatistico</h2>
<div class="line-block">     O modelo estatístico para a análise dos
dados oriundos de um DIC com um único fator de tratamentos é dado pela
<a href="">Equação 2</a>.</div>
<span class="math display">\[\begin{equation}
y_{ij} = \mu + \tau_i + e_{ij} = \mu_i + e_{ij}  \text{(2)}

\end{equation}\]</span>
<p>em que:</p>
<ul>
<li><p><span class="math inline">\(y_{ij}\)</span> é o valor observado
na j-ésima repetição do iésimo tratamento, com:</p></li>
<li><p><span class="math inline">\(i = 1, ... , I\)</span> e</p></li>
<li><p><span class="math inline">\(j = 1, ... , n_i\)</span></p></li>
<li><p><span class="math inline">\(\mu\)</span> é uma constante inerente
a todas as observações, geralmente a média geral,</p></li>
<li><p><span class="math inline">\(\tau_i\)</span> é o efeito do iésimo
tratamento,</p></li>
<li><p><span class="math inline">\(e_{ij}\)</span> é o erro
experimental, tal que <span class="math inline">\(e_{ij}
\overset{iid}{\sim} N(0,\sigma^2)\)</span>.</p></li>
</ul>
<div class="line-block">     Realizando-se a ANOVA, testamos as
hipóteses:</div>
<p><span class="math display">\[H_0 : \tau_{1} = \tau_{2} = ... =
\tau_{I} = 0\]</span></p>
<p><span class="math display">\[H_1 = H_a : \tau_{i} \neq 0\]</span></p>
<div class="line-block">     Havendo uma reparametrização do modelo
apresentado na <a href="#id_#%20Modelo%20estatistico">equação 2</a>, tal
que <span class="math inline">\(\mu + \tau_i = \alpha_i\)</span> em que
<span class="math inline">\(\alpha_i\)</span> é a média do iésimo
tratamento, é:</div>
<p><span class="math display">\[y_{ij} = \alpha_i + e_{ij}
\text{(3)}\]</span></p>
<div class="line-block">     As hipóteses de interesse passam a
ser:</div>
<p><span class="math display">\[H_0 : \alpha_1 = \alpha_2 = ... =
\alpha_I = \mu\]</span></p>
<p><span class="math display">\[H_1 = Ha : \text{pelo um contraste de
médias difere de zero}\]</span>.</p>
<div class="line-block">     Neste momento assumiremos que as
pressuposições de normalidade e independência dos erros, bem a
homogeneidade de suas variâncias garantidas. Assim, assumimos que eij
corresponde a uma realização da variável <span
class="math inline">\(E_{ij}\)</span> , tal que <span
class="math inline">\(e_{ij} \overset{iid}{\sim} N(0,\sigma^2)\)</span>
e os demais termos no <a href="">equação (3)</a> são fixos. Cabe
sailentar que o modelo citado é o modelo maximal, ou seja, aquele modelo
mais complicado a ser considerado na análise.<br />
     Desse modo, a esperança da variável aleatória <span
class="math inline">\(Y_{ij}\)</span> será</div>
<p><span class="math display">\[E(Y_{ij}) = E(\mu + \tau_i + E_{ij} ) =
\mu + \tau_i + 0 = \mu + \tau_i \text(4)\]</span></p>
<div class="line-block"><br />
<br />
</div>
</div>
<div id="análise-de-variância" class="section level2">
<h2>Análise de variância</h2>
<div class="line-block">    A proposta da ANOVA consiste em decompor a
variância total dos dados em parte atribuída aos efeitos de tratamentos
e parte ao acaso.</div>
<p>Tabela 1: Demonstração sobre fontes de variação e graus de
liberdade</p>
<table>
<thead>
<tr class="header">
<th>Fontes de Variação</th>
<th align="center">Graus de liberdade</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Total</td>
<td align="center"><span class="math inline">\(n\text{-}1\)</span></td>
</tr>
<tr class="even">
<td>Tratamentos</td>
<td align="center"><span class="math inline">\(I\text{-}1\)</span></td>
</tr>
<tr class="odd">
<td>Resíduo</td>
<td align="center"><span class="math inline">\(n\text{-}I\)</span></td>
</tr>
</tbody>
</table>
<div class="line-block">    Sabemos que a variância dos dados é dada
por:</div>
<p><span class="math display">\[\text{Variância} = \sum _{ij}
\frac{(yij−\bar{y})^2}{(n−1)} (\text{expressão 1})\]</span></p>
<p><span class="math display">\[\text{variância} =
\displaystyle{\frac{\text{SQ}}{\text{gl}}}(\text{expressão
2})\]</span></p>
<p><span class="math display">\[\text{F} =
\displaystyle{\frac{\text{QM}_{\text{Trat}}}{\text{QM}_{\text{Resíduo}}}}\]</span></p>
<p>Retomando as hipóteses</p>
<p><span class="math inline">\(H_0 : \mu_1 = \mu_2 = ... = \mu_I =
0\)</span></p>
<p><span class="math inline">\(H_1 = Ha\)</span>: pelo um contraste de
médias difere de zero.Denotamos por Soma de Quadrados do Total (SQ
Total) o numerador da <a href="#exp3">expressão 2</a>. Observe que a
decomposição mencionada anteriormente será:</p>
<p><span
class="math display">\[\displaystyle{\sum_{i=1}^I\sum_{j=1}^Jy_{ij}^2\text-\frac{\left(\sum_{i=1}^I\sum_{j=1}^Jy_{ij}\right)^2}{I\times
J}}(\text{expressão 3})\]</span></p>
<div class="line-block">    Em que SQ Tratamentos e SQ Resíduo
correspondem às Soma de Quadrados de Tratamentos e Soma de Quadrados de
Resíduo, respectivamente.<br />
    As expressões apresentadas em 4 e 5, podem ser reescritas conforme
segue.</div>
<p><span class="math display">\[\displaystyle{\frac{1}{J}\sum_{i=1}^I
T_i^2 \text-
\frac{\left(\sum_{i=1}^I\sum_{j=1}^Jy_{ij}\right)^2}{I\times
J}}(\text{expressão 4})\]</span></p>
<div class="line-block">    A SQ Resíduo pode ser obtida por diferença,
ou seja,</div>
<p>SQ Resíduo = SQ Total - SQ Tratamentos.</p>
<div class="line-block">    Para encontrarmos a estatística apropriada
para o teste F temos que obter as Esperanças dos Quadrados Médios
relacionados a cada fonte de variação na ANOVA.<br />
    Os quadrados médios, denotados usualmente por QM, são definidos pelo
quociente entre a soma de quadrados e o respectivo número de graus de
liberdade relacionados a uma fonte de varição, isto é:</div>
<p><span class="math display">\[\text{QM}_{\text{Trat}} =
\displaystyle{\frac{\text{SQ}_\text{Trat}}{\text{gl}_\text{Trat}}}\]</span></p>
<div class="line-block">    Rejeita-se <span
class="math inline">\(H_0\)</span> se <span
class="math inline">\(F_{cal} \geq F_{tab_{(\alpha, I-1,
I(J-1))}}\)</span>, em que <span class="math inline">\(\alpha\)</span> é
o nível de significância, <span class="math inline">\(I-1\)</span> é o
número de graus de liberdade do numerador e <span
class="math inline">\(I(J-1)\)</span> é o número de graus de liberdade
do denominador.</div>
<p><a href="https://docs.ufpr.br/~vayego/pedeefes/tab_sned.pdf">Tabela
F</a></p>
<div class="float">
<img src="figs/tabelaf.PNG" alt="Tabela F" />
<div class="figcaption">Tabela F</div>
</div>
<div class="line-block"><br />
<br />
</div>
</div>
<div id="coeficiente-de-variação" class="section level2">
<h2>Coeficiente de variação</h2>
<div class="line-block">    O número de repetições pode estar associado
ao número de graus de liberdade do resíduo ; <span
class="math display">\[\text{gl}_{\text{Res}} \geq 12\]</span><br />
   O CV é adimensional, pode-se comparar a dispersão de variáveis com
diferentes unidades de medida.</div>
<p><span class="math display">\[\displaystyle{\text{CV}_{\%} =
100\frac{\hat{\sigma}}{\hat{\mu}} =
100\frac{\sqrt{\text{QM}_{\text{Res}}}}{\bar{y}}}\]</span></p>
<ul>
<li><p>CV <span class="math inline">\(&lt;\)</span> 10% : baixo</p></li>
<li><p>10% <span class="math inline">\(&lt;\)</span> CV <span
class="math inline">\(&gt;\)</span> 20% :médio</p></li>
<li><p>20% <span class="math inline">\(&lt;\)</span> CV <span
class="math inline">\(&gt;\)</span> 30% :alto</p></li>
<li><p>CV <span class="math inline">\(&gt;\)</span> 30% : muito
alto</p></li>
</ul>
<div class="line-block"><br />
<br />
</div>
</div>
<div id="exemplo-1" class="section level2">
<h2>Exemplo</h2>
<div class="line-block">    Considere os dados abaixo referentes à
produtividade de milho (kg/100m<span class="math inline">\(^2\)</span>)
de quatro diferentes variedades, em um experimento instalado segundo o
delineamento inteiramente casualizado, com cinco repetições.</div>
<p>Tabela 2: produtividade de milho (kg/100m<span
class="math inline">\(^2\)</span>) de quatro diferentes variedades</p>
<table>
<thead>
<tr class="header">
<th align="center">(Variedades)</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>total</th>
<th>média</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">A</td>
<td>25</td>
<td>26</td>
<td>20</td>
<td>23</td>
<td>21</td>
<td>115</td>
<td>23,00</td>
</tr>
<tr class="even">
<td align="center">B</td>
<td>31</td>
<td>25</td>
<td>28</td>
<td>27</td>
<td>24</td>
<td>135</td>
<td>27,00</td>
</tr>
<tr class="odd">
<td align="center">C</td>
<td>22</td>
<td>26</td>
<td>28</td>
<td>25</td>
<td>29</td>
<td>130</td>
<td>26,00</td>
</tr>
<tr class="even">
<td align="center">D</td>
<td>33</td>
<td>29</td>
<td>31</td>
<td>34</td>
<td>28</td>
<td>155</td>
<td>31,00</td>
</tr>
</tbody>
</table>
<p>Tabela 3: nomenclatura de dados</p>
<table>
<thead>
<tr class="header">
<th align="center">(Variedades)</th>
<th>1</th>
<th>2</th>
<th>3</th>
<th>4</th>
<th>5</th>
<th>total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="center">V1</td>
<td>y11</td>
<td>y12</td>
<td>y13</td>
<td>y14</td>
<td>y15</td>
<td>y1· = T1</td>
</tr>
<tr class="even">
<td align="center">V2</td>
<td>y21</td>
<td>y22</td>
<td>y23</td>
<td>y24</td>
<td>y25</td>
<td>y2· = T2</td>
</tr>
<tr class="odd">
<td align="center">V3</td>
<td>y31</td>
<td>y32</td>
<td>y33</td>
<td>y34</td>
<td>y35</td>
<td>y3· = T3</td>
</tr>
<tr class="even">
<td align="center">V4</td>
<td>y41</td>
<td>y42</td>
<td>y43</td>
<td>y44</td>
<td>y45</td>
<td>y4· = T4</td>
</tr>
</tbody>
</table>
<p>Análise descritiva:</p>
<p>Tabela 4: Análise descritivas dos dados</p>
<table>
<thead>
<tr class="header">
<th>Análise</th>
<th>A</th>
<th>B</th>
<th>C</th>
<th>D</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Soma</td>
<td>115,00</td>
<td>135,00</td>
<td>130,00</td>
<td>155,00</td>
</tr>
<tr class="even">
<td>Média</td>
<td>23,00</td>
<td>27,00</td>
<td>26,00</td>
<td>31,00</td>
</tr>
<tr class="odd">
<td>Variância</td>
<td>6,50</td>
<td>7,50</td>
<td>7,50</td>
<td>6,50</td>
</tr>
<tr class="even">
<td>Desvio-padrão</td>
<td>2,55</td>
<td>2,74</td>
<td>2,74</td>
<td>2,55</td>
</tr>
</tbody>
</table>
<p>Soma de Quadrados total</p>
<p><span class="math display">\[\text{SQ}_{\text{Total}} =
\displaystyle{\sum_{i=1}^4\sum_{j=1}^5y_{ij}^2 \text{-}
\frac{\left(\sum_{i=1}^4\sum_{j=1}^5y_{ij}\right)^2}{4\times5}}\]</span></p>
<p><span class="math display">\[ = \displaystyle{25^2 + 26^2 + \ldots +
28^2 \text{-} \frac{535^2}{20}}
= 275,75\]</span></p>
<p>Soma de Quadrados de tratamentos</p>
<p><span class="math display">\[\text{SQ}_{\text{Trat}} =
\displaystyle{\frac{1}{5}\sum_{i=1}^4 T_i^2 \text{-}
\frac{\left(\sum_{i=1}^4\sum_{j=1}^5y_{ij}\right)^2}{4\times5}}\]</span></p>
<p><span class="math display">\[= \displaystyle{\frac{1}{5}\left(115^2 +
135^2 + 130^2 + 155^2\right) - \frac{535^2}{20}}= 163,75\]</span></p>
<p>Soma de Quadrados do Resíduo</p>
<p><span class="math display">\[\text{SQ}_\text{Resíduo} =
\text{SQ}_{\text{Total}} \text{-} \text{SQ}_{\text{Trat}}\]</span> <span
class="math display">\[= 275,75 - 163,75 = 112,00\]</span></p>
<p>Quadrado médio tratamentos</p>
<p><span class="math display">\[\text{QM}_{\text{Trat}} =
\displaystyle{\frac{\text{SQ}_{\text{Trat}}}{\text{gl}_{\text{Trat}}}}
= \displaystyle{\frac{163,75}{3}} = 54,5833\]</span></p>
<p>Quadrado médio do resíduo</p>
<p><span class="math display">\[\text{QM}_{\text{Resíduo}} =
\displaystyle{\frac{\text{SQ}_{\text{Resíduo}}}{\text{gl}_{\text{Resíduo}}}}=\displaystyle{\frac{112,00}{16}}=
7,0000\]</span></p>
<p>F calculado</p>
<p><span class="math display">\[\text{F} =
\displaystyle{\frac{\text{QM}_{\text{Trat}}}{\text{QM}_{\text{Resíduo}}}}=\displaystyle{\frac{54,5833}{7,0000}}=
7,80\]</span></p>
<p>Tabela 5: ANOVA</p>
<table>
<colgroup>
<col width="16%" />
<col width="17%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th>Fontes</th>
<th>Graus de liberdade</th>
<th>Soma de Quadrados</th>
<th>Quadrado Médio</th>
<th>Fcal</th>
<th>Ftab</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Tratamentos</td>
<td>3</td>
<td>163,75</td>
<td>54,5833</td>
<td>7,80</td>
<td></td>
</tr>
<tr class="even">
<td>resıduo</td>
<td>16</td>
<td>112,00</td>
<td>7,0000</td>
<td></td>
<td></td>
</tr>
<tr class="odd">
<td>Total</td>
<td>19</td>
<td>275,75</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>F tabelado:</p>
<pre><code>#&gt; Valor crítico da distribuição F: 3,238872</code></pre>
<pre><code>#&gt;         1      2      3      4      5      6      7      8      9
#&gt; 1  161,45 199,50 215,71 224,58 230,16 233,99 236,77 238,88 240,54
#&gt; 2   18,51  19,00  19,16  19,25  19,30  19,33  19,35  19,37  19,38
#&gt; 3   10,13   9,55   9,28   9,12   9,01   8,94   8,89   8,85   8,81
#&gt; 4    7,71   6,94   6,59   6,39   6,26   6,16   6,09   6,04   6,00
#&gt; 5    6,61   5,79   5,41   5,19   5,05   4,95   4,88   4,82   4,77
#&gt; 6    5,99   5,14   4,76   4,53   4,39   4,28   4,21   4,15   4,10
#&gt; 7    5,59   4,74   4,35   4,12   3,97   3,87   3,79   3,73   3,68
#&gt; 8    5,32   4,46   4,07   3,84   3,69   3,58   3,50   3,44   3,39
#&gt; 9    5,12   4,26   3,86   3,63   3,48   3,37   3,29   3,23   3,18
#&gt; 10   4,96   4,10   3,71   3,48   3,33   3,22   3,14   3,07   3,02
#&gt; 11   4,84   3,98   3,59   3,36   3,20   3,09   3,01   2,95   2,90
#&gt; 12   4,75   3,89   3,49   3,26   3,11   3,00   2,91   2,85   2,80
#&gt; 13   4,67   3,81   3,41   3,18   3,03   2,92   2,83   2,77   2,71
#&gt; 14   4,60   3,74   3,34   3,11   2,96   2,85   2,76   2,70   2,65
#&gt; 15   4,54   3,68   3,29   3,06   2,90   2,79   2,71   2,64   2,59
#&gt; 16   4,49   3,63   3,24   3,01   2,85   2,74   2,66   2,59   2,54
#&gt; 17   4,45   3,59   3,20   2,96   2,81   2,70   2,61   2,55   2,49
#&gt; 18   4,41   3,55   3,16   2,93   2,77   2,66   2,58   2,51   2,46
#&gt; 19   4,38   3,52   3,13   2,90   2,74   2,63   2,54   2,48   2,42
#&gt; 20   4,35   3,49   3,10   2,87   2,71   2,60   2,51   2,45   2,39</code></pre>
<table style="width:100%;">
<colgroup>
<col width="2%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
<col width="10%" />
</colgroup>
<thead>
<tr class="header">
<th align="left"></th>
<th align="right">1</th>
<th align="right">2</th>
<th align="right">3</th>
<th align="right">4</th>
<th align="right">5</th>
<th align="right">6</th>
<th align="right">7</th>
<th align="right">8</th>
<th align="right">9</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td align="left">1</td>
<td align="right">161,447639</td>
<td align="right">199,500000</td>
<td align="right">215,707345</td>
<td align="right">224,583241</td>
<td align="right">230,161878</td>
<td align="right">233,986000</td>
<td align="right">236,768400</td>
<td align="right">238,882695</td>
<td align="right">240,543255</td>
</tr>
<tr class="even">
<td align="left">2</td>
<td align="right">18,512821</td>
<td align="right">19,000000</td>
<td align="right">19,164292</td>
<td align="right">19,246794</td>
<td align="right">19,296410</td>
<td align="right">19,329534</td>
<td align="right">19,353217</td>
<td align="right">19,370993</td>
<td align="right">19,384826</td>
</tr>
<tr class="odd">
<td align="left">3</td>
<td align="right">10,127964</td>
<td align="right">9,552095</td>
<td align="right">9,276628</td>
<td align="right">9,117182</td>
<td align="right">9,013455</td>
<td align="right">8,940645</td>
<td align="right">8,886743</td>
<td align="right">8,845239</td>
<td align="right">8,812300</td>
</tr>
<tr class="even">
<td align="left">4</td>
<td align="right">7,708647</td>
<td align="right">6,944272</td>
<td align="right">6,591382</td>
<td align="right">6,388233</td>
<td align="right">6,256056</td>
<td align="right">6,163132</td>
<td align="right">6,094211</td>
<td align="right">6,041044</td>
<td align="right">5,998779</td>
</tr>
<tr class="odd">
<td align="left">5</td>
<td align="right">6,607891</td>
<td align="right">5,786135</td>
<td align="right">5,409451</td>
<td align="right">5,192168</td>
<td align="right">5,050329</td>
<td align="right">4,950288</td>
<td align="right">4,875872</td>
<td align="right">4,818320</td>
<td align="right">4,772466</td>
</tr>
<tr class="even">
<td align="left">6</td>
<td align="right">5,987378</td>
<td align="right">5,143253</td>
<td align="right">4,757063</td>
<td align="right">4,533677</td>
<td align="right">4,387374</td>
<td align="right">4,283866</td>
<td align="right">4,206658</td>
<td align="right">4,146804</td>
<td align="right">4,099016</td>
</tr>
<tr class="odd">
<td align="left">7</td>
<td align="right">5,591448</td>
<td align="right">4,737414</td>
<td align="right">4,346831</td>
<td align="right">4,120312</td>
<td align="right">3,971523</td>
<td align="right">3,865969</td>
<td align="right">3,787043</td>
<td align="right">3,725725</td>
<td align="right">3,676675</td>
</tr>
<tr class="even">
<td align="left">8</td>
<td align="right">5,317655</td>
<td align="right">4,458970</td>
<td align="right">4,066181</td>
<td align="right">3,837853</td>
<td align="right">3,687499</td>
<td align="right">3,580580</td>
<td align="right">3,500464</td>
<td align="right">3,438101</td>
<td align="right">3,388130</td>
</tr>
<tr class="odd">
<td align="left">9</td>
<td align="right">5,117355</td>
<td align="right">4,256495</td>
<td align="right">3,862548</td>
<td align="right">3,633088</td>
<td align="right">3,481659</td>
<td align="right">3,373754</td>
<td align="right">3,292746</td>
<td align="right">3,229583</td>
<td align="right">3,178893</td>
</tr>
<tr class="even">
<td align="left">10</td>
<td align="right">4,964603</td>
<td align="right">4,102821</td>
<td align="right">3,708265</td>
<td align="right">3,478050</td>
<td align="right">3,325835</td>
<td align="right">3,217175</td>
<td align="right">3,135465</td>
<td align="right">3,071658</td>
<td align="right">3,020383</td>
</tr>
<tr class="odd">
<td align="left">11</td>
<td align="right">4,844336</td>
<td align="right">3,982298</td>
<td align="right">3,587434</td>
<td align="right">3,356690</td>
<td align="right">3,203874</td>
<td align="right">3,094613</td>
<td align="right">3,012330</td>
<td align="right">2,947990</td>
<td align="right">2,896223</td>
</tr>
<tr class="even">
<td align="left">12</td>
<td align="right">4,747225</td>
<td align="right">3,885294</td>
<td align="right">3,490295</td>
<td align="right">3,259167</td>
<td align="right">3,105875</td>
<td align="right">2,996120</td>
<td align="right">2,913358</td>
<td align="right">2,848565</td>
<td align="right">2,796375</td>
</tr>
<tr class="odd">
<td align="left">13</td>
<td align="right">4,667193</td>
<td align="right">3,805565</td>
<td align="right">3,410534</td>
<td align="right">3,179117</td>
<td align="right">3,025438</td>
<td align="right">2,915269</td>
<td align="right">2,832098</td>
<td align="right">2,766913</td>
<td align="right">2,714356</td>
</tr>
<tr class="even">
<td align="left">14</td>
<td align="right">4,600110</td>
<td align="right">3,738892</td>
<td align="right">3,343889</td>
<td align="right">3,112250</td>
<td align="right">2,958249</td>
<td align="right">2,847726</td>
<td align="right">2,764199</td>
<td align="right">2,698672</td>
<td align="right">2,645791</td>
</tr>
<tr class="odd">
<td align="left">15</td>
<td align="right">4,543077</td>
<td align="right">3,682320</td>
<td align="right">3,287382</td>
<td align="right">3,055568</td>
<td align="right">2,901295</td>
<td align="right">2,790465</td>
<td align="right">2,706627</td>
<td align="right">2,640797</td>
<td align="right">2,587626</td>
</tr>
<tr class="even">
<td align="left">16</td>
<td align="right">4,493999</td>
<td align="right">3,633723</td>
<td align="right">3,238872</td>
<td align="right">3,006917</td>
<td align="right">2,852409</td>
<td align="right">2,741311</td>
<td align="right">2,657197</td>
<td align="right">2,591096</td>
<td align="right">2,537666</td>
</tr>
<tr class="odd">
<td align="left">17</td>
<td align="right">4,451322</td>
<td align="right">3,591531</td>
<td align="right">3,196777</td>
<td align="right">2,964708</td>
<td align="right">2,809996</td>
<td align="right">2,698660</td>
<td align="right">2,614299</td>
<td align="right">2,547955</td>
<td align="right">2,494292</td>
</tr>
<tr class="even">
<td align="left">18</td>
<td align="right">4,413873</td>
<td align="right">3,554557</td>
<td align="right">3,159908</td>
<td align="right">2,927744</td>
<td align="right">2,772853</td>
<td align="right">2,661304</td>
<td align="right">2,576722</td>
<td align="right">2,510158</td>
<td align="right">2,456281</td>
</tr>
<tr class="odd">
<td align="left">19</td>
<td align="right">4,380750</td>
<td align="right">3,521893</td>
<td align="right">3,127350</td>
<td align="right">2,895107</td>
<td align="right">2,740057</td>
<td align="right">2,628318</td>
<td align="right">2,543534</td>
<td align="right">2,476770</td>
<td align="right">2,422699</td>
</tr>
<tr class="even">
<td align="left">20</td>
<td align="right">4,351243</td>
<td align="right">3,492828</td>
<td align="right">3,098391</td>
<td align="right">2,866081</td>
<td align="right">2,710890</td>
<td align="right">2,598978</td>
<td align="right">2,514011</td>
<td align="right">2,447064</td>
<td align="right">2,392814</td>
</tr>
</tbody>
</table>
<p><strong>Distribuição F</strong></p>
<pre><code>#&gt; Carregando pacotes exigidos: car
#&gt; Carregando pacotes exigidos: carData
#&gt; Carregando pacotes exigidos: sandwich</code></pre>
<p><img src="dic_files/figure-html/unnamed-chunk-5-1.png" width="672" /></p>
<p>Como <span class="math inline">\(\text{F} = 7. 80 &gt; 3. 24 =
\text{FTab}\)</span> (<span class="math inline">\(\alpha = 0. 05, 3,
16\)</span>), há evidências para rejeitarmos <span
class="math inline">\(H_0\)</span> ao nível de 5% de significância.
Desse modo, não podemos afirmar que todas as médias são iguais.</p>
<div class="line-block"><br />
<br />
</div>
</div>
</div>
<div id="atividade" class="section level1">
<h1>Atividade</h1>
<ol style="list-style-type: decimal">
<li>Responda verdadeiro ou falso:</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li><p>Para estudar o efeito de 3 manejos na cultura da cana-de açúcar,
um pesquisador fez um experimento coletando os teores de açúcar de 5
colmos e analisou a média dos mesmos. O experimento foi instalado
seguindo as curvas de nível do local no delineamento inteiramente
casualizado.
<select class='webex-select'><option value='blank'></option><option value=''>TRUE</option><option value='answer'>FALSE</option></select></p></li>
<li><p>O quadrado médio do resíduo representa a variância do
experimento.
<select class='webex-select'><option value='blank'></option><option value='answer'>TRUE</option><option value=''>FALSE</option></select></p></li>
</ol>
<ol start="2" style="list-style-type: decimal">
<li>Em um experimento de competição de dez cultivares de arroz para
avaliar a produtividade, instalado em um delineamento inteiramente
casualizado, os resultados (parciais) para a ANOVA foram os
seguintes:</li>
</ol>
<ol style="list-style-type: lower-alpha">
<li>Complete o quadro da ANOVA</li>
</ol>
<table style="width:100%;">
<colgroup>
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
<col width="16%" />
</colgroup>
<thead>
<tr class="header">
<th>Fonte</th>
<th align="center">GL</th>
<th align="center">SQ</th>
<th align="center">QM</th>
<th align="center">F Cal</th>
<th align="center">F Tab</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>cultivar</td>
<td
align="center"><input class='webex-solveme nospaces' size='1' data-answer='["9"]'/></td>
<td align="center">17564523</td>
<td
align="center"><input class='webex-solveme nospaces' size='10' data-answer='["1951613,66"]'/></td>
<td align="center">9.31</td>
<td align="center">2.39</td>
</tr>
<tr class="even">
<td>Resíduo</td>
<td
align="center"><input class='webex-solveme nospaces' size='2' data-answer='["20"]'/></td>
<td
align="center"><input class='webex-solveme nospaces' size='10' data-answer='["4192510,56"]'/></td>
<td
align="center"><input class='webex-solveme nospaces' size='9' data-answer='["209625,52"]'/></td>
<td
align="center"><input class='webex-solveme nospaces' size='1' data-answer='["9"]'/></td>
<td
align="center"><input class='webex-solveme nospaces' size='1' data-answer='["9"]'/></td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="center">29</td>
<td
align="center"><input class='webex-solveme nospaces' size='6' data-answer='["133722"]'/></td>
<td
align="center"><input class='webex-solveme nospaces' size='1' data-answer='["9"]'/></td>
<td
align="center"><input class='webex-solveme nospaces' size='1' data-answer='["9"]'/></td>
<td
align="center"><input class='webex-solveme nospaces' size='1' data-answer='["9"]'/></td>
</tr>
</tbody>
</table>
<style>
:root {
    --incorrect: #983E82;
    --incorrect_alpha: #983E82;
    --correct: #59935B;
    --correct_alpha: #59935BDD;
    --highlight: #467AAC;
}
  .webex-incorrect, input.webex-solveme.webex-incorrect,
  .webex-radiogroup label.webex-incorrect {
    border: 2px dotted var(--incorrect);
    background-color: var(--incorrect_alpha);
  }
  .webex-correct, input.webex-solveme.webex-correct,
  .webex-radiogroup label.webex-correct {
    border: 2px dotted var(--correct);
    background-color: var(--correct_alpha);
  }
  .webex-box, .webex-solution.open {
    border: 2px solid var(--highlight);n  }
  .webex-solution button, .webex-check-button {
    background-color: var(--highlight);
  }
</style>
<ol start="2" style="list-style-type: lower-alpha">
<li><p>Variável resposta:
<select class='webex-select'><option value='blank'></option><option value=''>linhas
de arroz</option><option value=''>Cultivar de
arroz</option><option value='answer'>produtividade</option></select></p></li>
<li><p>Tratamento:
<select class='webex-select'><option value='blank'></option><option value=''>linhas
de arroz</option><option value='answer'>Cultivar de
arroz</option><option value=''>produtividade</option></select></p></li>
<li><p>Parcelas:
<select class='webex-select'><option value='blank'></option><option value='answer'>linhas
de arroz</option><option value=''>Cultivar de
arroz</option><option value=''>produtividade</option></select></p></li>
</ol>
<ol start="3" style="list-style-type: decimal">
<li>Fonte: <a
href="https://agronomiar.github.io/livroagro/delineamento-inteiramente-casualizado.html"
class="uri">https://agronomiar.github.io/livroagro/delineamento-inteiramente-casualizado.html</a></li>
</ol>
<div class="line-block">     Um experimento foi conduzido com o objetivo
de estudar diferentes produtos para redução da perda de massa em
pós-colheita de frutos de romã. O experimento foi conduzido em
delineamento inteiramente casualizado com quatro repetições.</div>
<p>Os Tratamentos são:</p>
<ul>
<li>T1: Cera Externo</li>
<li>T2: Cera Externo + Interno</li>
<li>T3: Óleo de Laranja Externo</li>
<li>T4: Óleo de Laranja Interno + Externo</li>
<li>T5: Hipoclorito de sódio Externo</li>
<li>T6: Hipoclorito de sódio Interno + Externo</li>
</ul>
<p>Os resultados de perda de massa, em porcentagem, foram:</p>
<table>
<thead>
<tr class="header">
<th>Tratamentos</th>
<th>R1</th>
<th>R2</th>
<th>R3</th>
<th>R4</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>2.10</td>
<td>1.90</td>
<td>1.68</td>
<td>1.69</td>
</tr>
<tr class="even">
<td>2</td>
<td>1.62</td>
<td>1.82</td>
<td>1.73</td>
<td>1.54</td>
</tr>
<tr class="odd">
<td>3</td>
<td>2.62</td>
<td>2.24</td>
<td>2.99</td>
<td>2.62</td>
</tr>
<tr class="even">
<td>4</td>
<td>2.52</td>
<td>2.21</td>
<td>2.53</td>
<td>3.22</td>
</tr>
<tr class="odd">
<td>5</td>
<td>2.67</td>
<td>2.44</td>
<td>2.78</td>
<td>2.66</td>
</tr>
<tr class="even">
<td>6</td>
<td>2.17</td>
<td>2.27</td>
<td>2.17</td>
<td>2.04</td>
</tr>
</tbody>
</table>
<div class="line-block">    A partir dos dados fornecidos há diferença
significativa entre os tratamentos? calcule.</div>
<div class="line-block"><br />
</div>
<p>Faça o upload da resolução e tire suas dúvidas <a
href="https://forms.gle/LQ6mNE4DoR1Fk6px6">aqui</a></p>
<div class="line-block"><br />
</div>
</div>
<div id="resolução-comentada" class="section level1">
<h1>Resolução comentada</h1>
<p>1 a) FALSO. Como o experimento foi realizado em curvas de nível, não
seria possível utilzar o delineamento inteiramente casualizado por conta
da variação causada pelo ambiente.</p>
<p>1 b) VERDADEIRO. O quadrado médio do resíduo explicita quanto os
dados podem variar entre si pelo fato do acaso, sem necessariamento
terem efeito do tratamento.</p>
<p>2 a)</p>
<table>
<thead>
<tr class="header">
<th>Fonte</th>
<th align="center">GL</th>
<th align="center">SQ</th>
<th align="center">QM</th>
<th align="center">F Cal</th>
<th align="center">F Tab</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>cultivar</td>
<td align="center">9</td>
<td align="center">17564523</td>
<td align="center">1951613.66</td>
<td align="center">9.31</td>
<td align="center">2.39</td>
</tr>
<tr class="even">
<td>Resíduo</td>
<td align="center">20</td>
<td align="center">4192510.56</td>
<td align="center">209625.52</td>
<td align="center"></td>
<td align="center"></td>
</tr>
<tr class="odd">
<td>Total</td>
<td align="center">29</td>
<td align="center">21757034</td>
<td align="center"></td>
<td align="center"></td>
<td align="center"></td>
</tr>
</tbody>
</table>
<ul>
<li><p>São 10 cultivares, logo graus de liberdade do tratamento tem que
ser 9, como graus de liberdade total são 29 temos que glresiduo = 29-9 =
20.</p></li>
<li><p><span class="math inline">\(QM tratamento = \frac{SQ tratamento}
{Gltratamento} = \frac{17564523}{9} = 1951613.66\)</span></p></li>
<li><p><span class="math inline">\(Fcal = \frac{QMtratamento}{QMresiduo}
\Rightarrow {QMresiduo}= \frac{QMtratamento}{Fcal} =
\frac{1951613.66}{9.31}= 209625.52\)</span></p></li>
<li><p><span class="math inline">\(QMresiduo=
\frac{SQresiduo}{Glresiduo} \Rightarrow SQresiduo = QMresiduo \times
Glresiduo = 209625.52 \times 20 = 4192510.56\)</span></p></li>
<li><p><span class="math inline">\(SQtotal = SQresiduo + SQtratamento =
17564523 + 4192510.56 = 21757034\)</span></p></li>
</ul>
<p>2 b) Resposta</p>
<p>Parcelas <span class="math inline">\(\rightarrow\)</span> linhas de
arroz</p>
<p>Tratamento <span class="math inline">\(\rightarrow\)</span> Cultivar
de arroz</p>
<p>Variavel resposta <span class="math inline">\(\rightarrow\)</span>
produtividade</p>
<ol start="3" style="list-style-type: decimal">
<li></li>
</ol>
<pre class="r"><code>resproma=c(2.10,1.90,1.68,1.69,1.62,1.82,1.73,1.54,2.62,2.24,2.99,2.62,
       2.52,2.21,2.53,3.22,2.67,2.44,2.78,2.66,2.17,2.27,2.17,2.04)
tratroma=as.factor(rep(paste(&quot;T&quot;,1:6, sep=&quot;&quot;),e=4))

modeloexercicio3=aov(resproma~tratroma)
anova(modeloexercicio3) # Conferir GL
#&gt; Analysis of Variance Table
#&gt; 
#&gt; Response: resproma
#&gt;           Df Sum Sq Mean Sq F value    Pr(&gt;F)    
#&gt; tratroma   5 3,6921 0,73842  12,312 2,724e-05 ***
#&gt; Residuals 18 1,0796 0,05998                      
#&gt; ---
#&gt; Signif. codes:  0 &#39;***&#39; 0,001 &#39;**&#39; 0,01 &#39;*&#39; 0,05 &#39;.&#39; 0,1 &#39; &#39; 1</code></pre>
<pre><code>#&gt; Valor crítico da distribuição F: 2,772853</code></pre>
<p><img src="dic_files/figure-html/unnamed-chunk-11-1.png" width="672" /></p>
<p>Portanto como Fcal &gt; Ftab pode-se concluir que há diferença entre
os tratamentos</p>
</div>



</div>
</div>

</div>

<script>

// add bootstrap table styles to pandoc tables
function bootstrapStylePandocTables() {
  $('tr.odd').parent('tbody').parent('table').addClass('table table-condensed');
}
$(document).ready(function () {
  bootstrapStylePandocTables();
});


</script>

<!-- tabsets -->

<script>
$(document).ready(function () {
  window.buildTabsets("TOC");
});

$(document).ready(function () {
  $('.tabset-dropdown > .nav-tabs > li').click(function () {
    $(this).parent().toggleClass('nav-tabs-open');
  });
});
</script>

<!-- code folding -->

<script>
$(document).ready(function ()  {

    // temporarily add toc-ignore selector to headers for the consistency with Pandoc
    $('.unlisted.unnumbered').addClass('toc-ignore')

    // move toc-ignore selectors from section div to header
    $('div.section.toc-ignore')
        .removeClass('toc-ignore')
        .children('h1,h2,h3,h4,h5').addClass('toc-ignore');

    // establish options
    var options = {
      selectors: "h1,h2,h3",
      theme: "bootstrap3",
      context: '.toc-content',
      hashGenerator: function (text) {
        return text.replace(/[.\\/?&!#<>]/g, '').replace(/\s/g, '_');
      },
      ignoreSelector: ".toc-ignore",
      scrollTo: 0
    };
    options.showAndHide = true;
    options.smoothScroll = true;

    // tocify
    var toc = $("#TOC").tocify(options).data("toc-tocify");
});
</script>

<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
